version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: columbia
    ports:
      - 5432:5432
  
  app:
    image: de350860aff8
    ports:
      - "8080:8080"
    depends_on:
      - db
