version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: columbia
    ports:
      - 5432:5432
  
  app:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/restapi
    ports:
      - "8080:8080"
    depends_on:
      - db